# Generated by Django 4.2.7 on 2025-04-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='Тип оборудования')),
                ('request_date', models.DateTimeField(verbose_name='Желаемая дата')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('APPROVED', 'Подтверждено'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на обслуживание',
                'verbose_name_plural': 'Заявки на обслуживание',
            },
        ),
    ]
