# Generated by Django 4.2.7 on 2025-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='ФИО клиента'),
            preserve_default=False,
        ),
    ]
