# Generated by Django 4.2.7 on 2025-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_engineer_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
