# Generated by Django 4.2.7 on 2025-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicerequest_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (9:00–12:00)'), ('afternoon', 'Afternoon (12:00–15:00)'), ('evening', 'Evening (15:00–18:00)')], max_length=20, null=True),
        ),
    ]
