# Generated by Django 5.2.1 on 2025-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicerequest_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор')], default='USER', max_length=20),
        ),
    ]
