# Generated by Django 5.2.1 on 2025-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_engineer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор')], default='USER', max_length=20),
        ),
    ]
