# Generated by Django 5.2.1 on 2025-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_engineer_role_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
